<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\field\Entity\FieldConfig;
use Drupal\field\Entity\FieldStorageConfig;

/**
 * Implements hook_form_alter().
 */
function bee_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_type_edit_form' || $form_id == 'node_type_add_form') {
    if (\Drupal::currentUser()->hasPermission('administer bee settings')) {
      $node_type = $form_state->getFormObject()->getEntity();

      $bee_settings = \Drupal::config('node.type.' . $node_type->id())->get('bee');

      $form['bee'] = [
        '#type' => 'details',
        '#title' => t('BEE'),
        '#group' => 'additional_settings',
        '#tree' => TRUE,
      ];
      $form['bee']['bookable'] = [
        '#type' => 'checkbox',
        '#title' => t('Make this entity type bookable'),
        '#default_value' => isset($bee_settings['bookable']) ? $bee_settings['bookable'] : 0,
      ];
      $form['bee']['bookable_type'] = [
        '#type' => 'container',
        'radios' => [
          '#type' => 'radios',
          '#options' => [
            'daily' => t('Daily Bookings'),
            'hourly' => t('Hourly Bookings'),
          ],
          '#default_value' => isset($bee_settings['bookable_type']) ? $bee_settings['bookable_type'] : 'daily',
        ],
        '#states' => [
          'visible' => [
            ':input[name="bee[bookable]"]' => ['checked' => TRUE],
          ],
        ],
      ];

      if (isset($bee_settings['type_id'])) {
        $form['bee']['type_id'] = [
          '#type' => 'hidden',
          '#value' => $bee_settings['type_id'],
        ];
      }

      $form['actions']['submit']['#submit'][] = 'bee_node_type_edit_form_submit';

      $form['#attached']['library'][] = 'bee/bee';
    }
  }
}

/**
 * Custom submit function for the node_type_edit_form and node_type_add_form.
 */
function bee_node_type_edit_form_submit(array &$form, FormStateInterface $form_state) {
  $node_type = $form_state->getFormObject()->getEntity();

  $bee_settings = $form_state->getValue('bee');

  $bee_settings['bookable_type'] = $bee_settings['bookable_type']['radios'];

  if ($bee_settings['bookable']) {
    $field_name = 'field_availability_' . $bee_settings['bookable_type'];

    $field_storage = FieldStorageConfig::loadByName('node', $field_name);
    $field = FieldConfig::loadByName('node', $node_type->id(), $field_name);

    if (empty($field_storage)) {
      $field_storage = FieldStorageConfig::create([
        'field_name' => $field_name,
        'entity_type' => 'node',
        'type' => 'entity_reference',
        'cardinality' => 1,
        'locked' => 1,
        'settings' => [
          'target_type' => 'bat_unit',
        ],
      ]);
      $field_storage->save();
    }

    if (empty($field)) {
      $field = FieldConfig::create([
        'field_storage' => $field_storage,
        'entity_type' => 'node',
        'label' => 'Availability',
        'bundle' => $node_type->id(),
        'required' => FALSE,
        'settings' => [
          'handler' => 'default',
          'handler_settings' => [],
        ],
      ]);
      $field->save();
    }

    $view_display = \Drupal::entityTypeManager()->getStorage('entity_view_display')->load('node.' . $node_type->id() . '.default');
    $view_display->setComponent($field_name, [
      'type' => 'entity_reference_entity_view',
      'region' => 'content',
      'label' => 'above',
      'settings' => [
        'view_mode' => $bee_settings['bookable_type'] . '_calendar',
      ],
    ]);
    $view_display->save();

    if (!isset($bee_settings['type_id'])) {
      $bat_type = bat_type_create(
        [
          'name' => $node_type->label(),
          'type' => $bee_settings['bookable_type'],
        ]
      );

      $state = bat_event_load_state_by_machine_name('bee_' . $bee_settings['bookable_type'] . '_available');
      $bat_type->set('field_availability_' . $bee_settings['bookable_type'], $state->id());

      bat_type_save($bat_type);

      $bee_settings['type_id'] = $bat_type->id();
    }

    \Drupal::configFactory()->getEditable('node.type.' . $node_type->id())->set('bee', $bee_settings)->save();
  }
  else {
    if (isset($bee_settings['type_id'])) {
      $node_storage = \Drupal::entityManager()->getStorage('node');

      $query = \Drupal::entityQuery('node')
        ->condition('type', $node_type->id());

      $nids = $query->execute();
      foreach ($node_storage->loadMultiple($nids) as $node) {
        if ($node->hasField('field_availability_' . $bee_settings['bookable_type'])) {
          $bat_unit = $node->get('field_availability_' . $bee_settings['bookable_type'])->entity;
          bat_unit_delete($bat_unit);
        }
      }

      $bat_type = bat_type_load($bee_settings['type_id']);
      $bat_type->delete();
    }

    \Drupal::configFactory()->getEditable('node.type.' . $node_type->id())->clear('bee')->save();
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function bee_node_insert(EntityInterface $node) {
  $bee_settings = \Drupal::config('node.type.' . $node->bundle())->get('bee');

  if (isset($bee_settings['bookable']) && $bee_settings['bookable']) {
    $bat_unit = bat_unit_create(
      [
        'name' => $node->label(),
        'type' => 'default',
        'unit_type_id' => $bee_settings['type_id'],
      ]
    );
    bat_unit_save($bat_unit);

    $node->set('field_availability_' . $bee_settings['bookable_type'], $bat_unit->id());
    $node->setNewRevision(FALSE);
    $node->save();
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function bee_node_delete(EntityInterface $node) {
  $bee_settings = \Drupal::config('node.type.' . $node->bundle())->get('bee');

  if ($node->hasField('field_availability_' . $bee_settings['bookable_type'])) {
    if ($bat_unit = $node->get('field_availability_' . $bee_settings['bookable_type'])->entity) {
      bat_unit_delete($bat_unit);
    }
  }
}

/**
 * Implements hook_entity_view_alter().
 */
function bee_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($entity->getEntityTypeId() == 'bat_unit') {
    if ($display->id() == 'bat_unit.default.daily_calendar' || $display->id() == 'bat_unit.default.hourly_calendar') {
      $bat_type = $entity->get('unit_type_id')->entity;

      $unit_type = $bat_type->id();

      if ($bat_type->bundle() == 'daily') {
        $event_type = 'availability_daily';
        $event_granularity = 'bat_daily';

        $fc_user_settings = [
          'batCalendar' => [
            [
              'unitType' => $unit_type,
              'unitIds' => $entity->id(),
              'eventType' => $event_type,
              'eventGranularity' => $event_granularity,
              'editable' => FALSE,
              'selectable' => FALSE,
              'defaultView' => 'month',
              'views' => 'month',
              'headerLeft' => 'today',
              'headerCenter' => 'title',
              'headerRight' => 'prev, next',
              'resourceLabelText' => ' ',
              'background' => 'hide-book',
            ],
          ],
        ];
      }
      else {
        $event_type = 'availability_hourly';
        $event_granularity = 'bat_hourly';

        $fc_user_settings = [
          'batCalendar' => [
            [
              'unitType' => $unit_type,
              'unitIds' => $entity->id(),
              'eventType' => $event_type,
              'eventGranularity' => $event_granularity,
              'editable' => FALSE,
              'selectable' => FALSE,
              'defaultView' => 'timelineDay',
              'views' => 'timelineDay',
              'viewsTimelineDaySlotDuration' => '01:00',
              'headerLeft' => 'today',
              'headerCenter' => 'title',
              'headerRight' => 'prev, next',
              'resourceLabelText' => ' ',
              'background' => 'hide-book',
            ],
          ],
        ];
      }

      $calendar_settings['user_settings'] = $fc_user_settings;
      $calendar_settings['calendar_id'] = 'fullcalendar-scheduler';

      $render_array = [
        'calendar' => [
          '#theme' => 'bat_fullcalendar',
          '#calendar_settings' => $calendar_settings,
          '#attached' => ['library' => ['bat_event_ui/bat_event_ui', 'bat_fullcalendar/bat-fullcalendar-scheduler']],
        ],
      ];

      $build = array(
        '#markup' => render($render_array),
      );
    }
  }
}

/**
 * Implements hook_bat_api_events_index_calendar_alter().
 */
function bee_bat_api_events_index_calendar_alter(&$events, $context) {
  if ($context['background'] == 'hide-book') {
    foreach ($events as $id => $event) {
      if ($event['type'] == 'availability_daily' || $event['type'] == 'availability_hourly') {
        unset($events[$id]['rendering']);

        if ($event['blocking']) {
          if ($event['type'] == 'availability_daily') {
            $state = bat_event_load_state_by_machine_name('bee_daily_not_available');
          }
          else {
            $state = bat_event_load_state_by_machine_name('bee_hourly_not_available');
          }

          $events[$id]['color'] = $state->getColor();
          $events[$id]['title'] = $state->getCalendarLabel();
        }

        $start_date = new DateTime($event['start']);
        $end_date = new DateTime($event['end']);

        if ($start_date->format('Y-m-d') != $end_date->format('Y-m-d')) {
          $events[$id]['end'] = $end_date->add(new DateInterval('P1D'))->format('Y-m-d') . 'T00:00:00';
        }
      }
    }
  }
}
